services:
  mongodb:
    image: mongo:5.0.15
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 123456
    volumes:
      - ./data/mongodb:/data/db

volumes:
  mongodb_data_container:

    # docker compose -p system-management up -d